# Enable C++ support
language: cpp

# Install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get install -y libhdf5-dev

install:
  - sudo apt-get install -qq g++5.1
  - export CXX="g++5.1"

# Compiler selection
compiler:
  - gcc
  
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
