# Install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libhdf5-dev

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
